# Generated by Django 4.2.4 on 2023-09-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('reps', models.IntegerField(verbose_name='Reps')),
                ('sets', models.IntegerField(verbose_name='Sets')),
                ('kg', models.IntegerField(verbose_name='Kg')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
